In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import copy
from synthesizer import Synthesizer
from generator import Generator
from algorithm import Algorithm

warnings.filterwarnings('ignore')
plt.rcParams['figure.dpi'] = 80
plt.rcParams['axes.grid'] = True
sns.set()

In [2]:
# series_type = "default"
# from_start=False
# a, b = -40, 40
# train_window = 10

# generators = []
# for rs in 5 * np.arange(2, 14) + 1:
#     synt = Synthesizer(series_type, dim=10, low=-10, high=10, clip=(a, b),
#                        noise_var=1, workers_num=3, random_seed=rs)
#     gen = Generator(series_type, synt)
#     gen.generate(length=1500, from_start=from_start, lower_bound=100, upper_bound=400, alternating=True)
#     generators.append(gen)

#     --//-- dim=20, low=-10, high=10, clip=(2 * a, 2 * b)
#     --//-- dim=40, low=-10, high=10, clip=(4 * a, 4 * b)
# ...
# best = weight_hypers["simple_105"] # for alpha experiments

In [3]:
from main import df_w
from main import df_a

100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:45<00:00, 47.08it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.43it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.98it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:46<00:00, 46.37it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:46<00:00, 46.27it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.67it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.81it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.90it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:46<00:00, 46.23it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.49it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:46<00:00, 46.02it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.97it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.45it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:48<00:00, 44.88it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.81it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.62it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:46<00:00, 46.32it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:46<00:00, 46.26it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:48<00:00, 44.97it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:46<00:00, 46.18it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:46<00:00, 46.47it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.55it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.77it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.69it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.61it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:46<00:00, 46.18it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.80it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.81it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.86it/s]
100%|████████████████████████████████████████████████████████████████████████| 2162/2162 [00:47<00:00, 45.43it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.74it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.68it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 41.91it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.51it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 41.71it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 42.14it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.77it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.62it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:56<00:00, 40.85it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 42.30it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 41.99it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 41.97it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.34it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 42.12it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 42.21it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.34it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.47it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 41.91it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 42.25it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.57it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.69it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:54<00:00, 42.43it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 42.28it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 41.63it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 41.88it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:55<00:00, 41.86it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [01:00<00:00, 38.77it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [01:01<00:00, 38.16it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:57<00:00, 40.43it/s]
100%|████████████████████████████████████████████████████████████████████████| 2328/2328 [00:56<00:00, 41.52it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:57<00:00, 40.52it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:55<00:00, 41.72it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:54<00:00, 42.20it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:54<00:00, 42.15it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:54<00:00, 42.49it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:54<00:00, 42.71it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:54<00:00, 42.49it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:54<00:00, 42.62it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:55<00:00, 41.99it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:54<00:00, 42.09it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:56<00:00, 40.90it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 44.43it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:51<00:00, 44.57it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:51<00:00, 44.64it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:51<00:00, 44.54it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 43.88it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 43.73it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:53<00:00, 43.16it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:51<00:00, 44.71it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:51<00:00, 45.02it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:51<00:00, 44.90it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:51<00:00, 44.90it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 44.13it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 43.91it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 44.00it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 44.23it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 44.13it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 44.25it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:52<00:00, 44.30it/s]
100%|████████████████████████████████████████████████████████████████████████| 2315/2315 [00:53<00:00, 43.59it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:54<00:00, 43.22it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 42.67it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:56<00:00, 42.26it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:57<00:00, 41.38it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 42.82it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 42.62it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 42.86it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:54<00:00, 43.40it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:54<00:00, 43.33it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:54<00:00, 43.30it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 43.10it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 43.00it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 42.64it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 42.98it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 42.65it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:54<00:00, 43.39it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 43.14it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:56<00:00, 42.26it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [01:02<00:00, 37.73it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [01:04<00:00, 36.72it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [01:13<00:00, 32.11it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [01:14<00:00, 31.77it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [01:16<00:00, 30.94it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [01:13<00:00, 32.37it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [01:02<00:00, 37.85it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:57<00:00, 41.16it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:57<00:00, 41.62it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:56<00:00, 42.17it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 42.96it/s]
100%|████████████████████████████████████████████████████████████████████████| 2375/2375 [00:55<00:00, 42.60it/s]

In [4]:
df_w.transpose()

,default,simple_105,simple_11,simple_12,simple_2
weights_function,1 / ((x + 1) * (ln(x + 1))^2),1 / (x^1.05),1 / (x^1.1),1 / (x^1.2),1 / (x^2)
1,79840.647596,57246.032758,57979.263277,59404.305653,72496.334055
2,157716.686699,125714.7126,127028.209181,130475.667787,153617.994598
3,168503.632982,132625.765717,134273.2528,138334.486094,181534.904141
4,87111.003424,61961.538837,63309.957725,65618.113142,75112.308185
5,-151392.323852,-181086.277817,-179865.648309,-176831.899965,-158716.11087
6,202083.205652,162875.664622,165197.853735,170518.863363,218850.131204
7,98238.138604,70910.636363,72276.429439,74698.623118,89298.122993
8,160503.623479,121457.147702,123684.889136,128709.828368,158863.215689
9,201318.774218,166048.12834,167892.435349,172562.256496,227390.435679
10,110173.030013,80673.380374,82209.39572,84859.715497,90110.910791
11,215624.969274,173997.624967,176573.551022,182562.605354,227181.960228
12,228498.945869,-246951.35167,-244283.553286,192978.232944,264168.241888

In [19]:
indexes_1 = [3*k+1 for k in range(4)]
indexes_2 = [3*k+2 for k in range(4)]
indexes_4 = [3*k+3 for k in range(4)]

df_w1 = df_w[["weights_function"] + indexes_1].rename(columns={idx: f"random-{idx // 3 + 1}" for idx in indexes_1})
df_w2 = df_w[["weights_function"] + indexes_2].rename(columns={idx: f"random-{idx // 3 + 1}" for idx in indexes_2})
df_w4 = df_w[["weights_function"] + indexes_4].rename(columns={idx: f"random-{idx // 3}" for idx in indexes_4})

df_a1 = df_a[["alpha_function"] + indexes_1].rename(columns={idx: f"random-{idx // 3 + 1}" for idx in indexes_1})
df_a2 = df_a[["alpha_function"] + indexes_2].rename(columns={idx: f"random-{idx // 3 + 1}" for idx in indexes_2})
df_a4 = df_a[["alpha_function"] + indexes_4].rename(columns={idx: f"random-{idx // 3}" for idx in indexes_4})

In [20]:
df_w1

,weights_function,random-1,random-2,random-3,random-4
default,1 / ((x + 1) * (ln(x + 1))^2),79840.647596,87111.003424,98238.138604,110173.030013
simple_105,1 / (x^1.05),57246.032758,61961.538837,70910.636363,80673.380374
simple_11,1 / (x^1.1),57979.263277,63309.957725,72276.429439,82209.39572
simple_12,1 / (x^1.2),59404.305653,65618.113142,74698.623118,84859.715497
simple_2,1 / (x^2),72496.334055,75112.308185,89298.122993,90110.910791

In [21]:
df_w2

,weights_function,random-1,random-2,random-3,random-4
default,1 / ((x + 1) * (ln(x + 1))^2),157716.686699,-151392.323852,160503.623479,215624.969274
simple_105,1 / (x^1.05),125714.7126,-181086.277817,121457.147702,173997.624967
simple_11,1 / (x^1.1),127028.209181,-179865.648309,123684.889136,176573.551022
simple_12,1 / (x^1.2),130475.667787,-176831.899965,128709.828368,182562.605354
simple_2,1 / (x^2),153617.994598,-158716.11087,158863.215689,227181.960228

In [22]:
df_w4

,weights_function,random-1,random-2,random-3,random-4
default,1 / ((x + 1) * (ln(x + 1))^2),168503.632982,202083.205652,201318.774218,228498.945869
simple_105,1 / (x^1.05),132625.765717,162875.664622,166048.12834,-246951.35167
simple_11,1 / (x^1.1),134273.2528,165197.853735,167892.435349,-244283.553286
simple_12,1 / (x^1.2),138334.486094,170518.863363,172562.256496,192978.232944
simple_2,1 / (x^2),181534.904141,218850.131204,227390.435679,264168.241888

In [23]:
df_a1

,alpha_function,random-1,random-2,random-3,random-4
default,1 / (x + 1),57246.032758,61961.538837,70910.636363,80673.380374
simple_11,1 / (x + 1)^1.1,54204.991451,59354.718381,67808.135137,76626.00077
simple_13,1 / (x + 1)^1.3,53312.744821,57634.297737,66492.104495,73147.335656
simple_15,1 / (x + 1)^1.5,59385.53529,60600.812353,72581.673603,78011.929897
simple_2,1 / (x + 1)^2),66192.510515,63556.96846,79602.279424,83652.422596

In [24]:
df_a2

,alpha_function,random-1,random-2,random-3,random-4
default,1 / (x + 1),125714.7126,-181086.277817,121457.147702,173997.624967
simple_11,1 / (x + 1)^1.1,122233.566518,-185145.421396,119201.429614,171383.557002
simple_13,1 / (x + 1)^1.3,115968.270436,-188417.183463,116735.82592,170079.973453
simple_15,1 / (x + 1)^1.5,115165.661238,-183052.535076,120482.953033,177253.548597
simple_2,1 / (x + 1)^2),124818.941976,-169220.682813,127982.114243,198593.851087

In [25]:
df_a4

,alpha_function,random-1,random-2,random-3,random-4
default,1 / (x + 1),132625.765717,162875.664622,166048.12834,-246951.35167
simple_11,1 / (x + 1)^1.1,129019.759952,160108.034566,165099.947835,-248488.374546
simple_13,1 / (x + 1)^1.3,127271.547042,159498.761137,166983.690103,-246352.175105
simple_15,1 / (x + 1)^1.5,134903.726929,168753.924218,178155.277842,-233282.243069
simple_2,1 / (x + 1)^2),168030.585993,195700.07168,221084.11541,247005.747062

In [26]:
df_w.to_csv("df_w.csv", sep='\t')
df_a.to_csv("df_a.csv", sep='\t')