In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings

# warnings.filterwarnings('ignore')
plt.rcParams['figure.dpi'] = 80

import sys
sys.path.insert(0, '..')

import os
from pathlib import Path

from hypers import weight_hypers
from hypers import alpha_hypers 

from experiment import Params
from experiment import run_experiments
from experiment import load_experiments
from experiment import draw_logs
from experiment import experiments_to_df

from analysis import draw_several
from analysis import extract_needed

In [76]:
experiments_10, df_10 = load_experiments('../results/experim_10.json')
experiments_11, df_11 = load_experiments('../results/experim_11.json')
experiments_12, df_12 = load_experiments('../results/experim_12.json')
experiments_13, df_13 = load_experiments('../results/experim_13.json')
experiments_14, df_14 = load_experiments('../results/experim_14.json')
experiments_15, df_15 = load_experiments('../results/experim_15.json')
experiments_16, df_16 = load_experiments('../results/experim_16.json')
experiments_17, df_17 = load_experiments('../results/experim_17.json')
experiments_18, df_18 = load_experiments('../results/experim_18.json')
experiments_19, df_19 = load_experiments('../results/experim_19.json')
experiments_20, df_20 = load_experiments('../results/experim_20.json')
experiments_21, df_21 = load_experiments('../results/experim_21.json')
experiments_22, df_22 = load_experiments('../results/experim_22.json')
experiments_23, df_23 = load_experiments('../results/experim_23.json')
experiments_24, df_24 = load_experiments('../results/experim_24.json')
experiments_25, df_25 = load_experiments('../results/experim_25.json')
experiments_26, df_26 = load_experiments('../results/experim_26.json')
experiments_27, df_27 = load_experiments('../results/experim_27.json')
experiments_28, df_28 = load_experiments('../results/experim_28.json')
experiments_29, df_29 = load_experiments('../results/experim_29.json')
experiments_30, df_30 = load_experiments('../results/experim_30.json')
experiments_31, df_31 = load_experiments('../results/experim_31.json')
experiments_32, df_32 = load_experiments('../results/experim_32.json')
experiments_33, df_33 = load_experiments('../results/experim_33.json')
experiments_34, df_34 = load_experiments('../results/experim_34.json')
experiments_35, df_35 = load_experiments('../results/experim_35.json')
experiments_36, df_36 = load_experiments('../results/experim_36.json')
experiments_37, df_37 = load_experiments('../results/experim_37.json')
experiments_38, df_38 = load_experiments('../results/experim_38.json')
experiments_39, df_39 = load_experiments('../results/experim_39.json')
experiments_40, df_40 = load_experiments('../results/experim_40.json')
experiments_41, df_41 = load_experiments('../results/experim_41.json')
experiments_42, df_42 = load_experiments('../results/experim_42.json')
experiments_43, df_43 = load_experiments('../results/experim_43.json')
experiments_44, df_44 = load_experiments('../results/experim_44.json')
experiments_45, df_45 = load_experiments('../results/experim_45.json')
experiments_46, df_46 = load_experiments('../results/experim_46.json')
experiments_47, df_47 = load_experiments('../results/experim_47.json')
experiments_48, df_48 = load_experiments('../results/experim_48.json')
experiments_49, df_49 = load_experiments('../results/experim_49.json')
experiments_50, df_50 = load_experiments('../results/experim_50.json')
experiments_51, df_51 = load_experiments('../results/experim_51.json')
experiments_52, df_52 = load_experiments('../results/experim_52.json')

In [61]:
experiments = experiments_17 + experiments_18 + experiments_19 + experiments_29 \
+ experiments_31 + experiments_33 + experiments_37 \
+ experiments_32 + experiments_49 + experiments_51 \
+ experiments_38 + experiments_48 + experiments_50

In [62]:
df = experiments_to_df(experiments)

In [69]:
pd.set_option('display.max_rows', None)
mt_mask = 1 #(df["mixing_type"] == "start") | (df["mixing_type"] == "uniform past")
table = df[(df["train_window"] == 10) & mt_mask]
# print(table[["weight_function", "mixing_type", "mean"]].to_latex(float_format="%.2f", index=False))
short = table[["alpha_function", "mixing_type", "weight_function", "mean"]]
# short
# print(short.to_latex(formatters= {"mean": lambda x: round(x / 10000, 2)}, index=False))
# print(short.to_latex(float_format="%.2f", index=False))
# short.shape

(168, 4)

In [82]:
df_11

,noise_var,train_window,weight_function,mixing_type,alpha_function,mean,random_0,random_1,random_2,random_3
1,1,5,1 / x,start,1 / (x + 1),186472.68,151169.81,148745.64,231898.43,214076.82
2,1,5,1 / (x^0.1),start,1 / (x + 1),150954.24,109597.55,133745.09,179190.82,181283.5
0,1,5,1 / (x^0.5),start,1 / (x + 1),159481.02,120807.78,138702.68,191938.53,186475.11
3,1,5,1 / (x^0.9),start,1 / (x + 1),177944.90,142126.35,144685.37,220190.63,204777.25
5,1,10,1 / x,start,1 / (x + 1),131907.11,116539.76,102028.36,164011.73,145048.6
6,1,10,1 / (x^0.1),start,1 / (x + 1),111276.08,95453.65,93462.35,133255.91,122932.39
4,1,10,1 / (x^0.5),start,1 / (x + 1),108630.68,93992.5,90539.95,131792.11,118198.15
7,1,10,1 / (x^0.9),start,1 / (x + 1),122832.21,108202.65,96706.47,152078.21,134341.5
9,1,20,1 / x,start,1 / (x + 1),125043.66,109571.99,99124.85,152158.13,139319.65
10,1,20,1 / (x^0.1),start,1 / (x + 1),136714.65,117012.7,118286.29,159607.31,151952.3
8,1,20,1 / (x^0.5),start,1 / (x + 1),121969.55,105647.55,104198.13,144176.01,133856.51
11,1,20,1 / (x^0.9),start,1 / (x + 1),120396.31,105715.51,97429.17,145251.65,133188.93
13,1,50,1 / x,start,1 / (x + 1),135507.98,120445.14,104671.71,168785.38,148129.68
14,1,50,1 / (x^0.1),start,1 / (x + 1),150648.35,132576.63,129760.49,176162.81,164093.47
12,1,50,1 / (x^0.5),start,1 / (x + 1),132490.50,117613.95,110901.76,158747.37,142698.94
15,1,50,1 / (x^0.9),start,1 / (x + 1),130892.45,116767.59,103081.17,161635.88,142085.16
17,1,100,1 / x,start,1 / (x + 1),147988.12,126851.7,111650.59,195422.19,158028.0
18,1,100,1 / (x^0.1),start,1 / (x + 1),159438.38,133701.8,135473.79,197839.72,170738.21
16,1,100,1 / (x^0.5),start,1 / (x + 1),142431.61,120292.74,116454.57,182560.89,150418.25
19,1,100,1 / (x^0.9),start,1 / (x + 1),143038.68,122351.6,109807.3,188097.05,151898.79

In [85]:
start  = experiments_10 + experiments_11 + experiments_17 + experiments_18 + experiments_19 + experiments_29 + experiments_52



needed_1 = {
    # 'random_seed': [104],
    'train_window': [10],
    # 'key_a': ["default"],
    'key_w': ["default", "const", "simple_101", "diverge_05"]
}

interesting = extract_needed(start, needed_1)

sdf = experiments_to_df(interesting)
print(sdf[["weight_function", "alpha_function", "mean"]].to_latex(float_format="%.2f", index=False))
# sdf[["weight_function", "alpha_function", "mean"]]

\begin{tabular}{llr}
\toprule
weight_function & alpha_function & mean \\
\midrule
1 / ((x + 1) * (ln(x + 1))^2) & 1 / (x + 10) & 175411.17 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / (x + 100) & 173760.98 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / (x + 1000) & 162129.20 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / (x + 1) & 175594.64 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / 100 & 220008.81 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / 500 & 198094.83 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / 1000 & 184324.73 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / 5000 & 147561.46 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / 10000 & 136414.42 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / 50000 & 130783.65 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / (x + 1)^0.5 & 245494.10 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / (x + 1)^1.5 & 130339.21 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / (x + 1)^2 & 136029.09 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / ln(x + 1) & 534269.18 \\
1 / ((x + 1) * (ln(x + 1))^2) & 1 / e^(x/3) & 136413.87 \\
1 / (x^1.01) & 1 / (x + 10) & 132208.09 \\
1 / (x^1.01) & 1 / (x + 100) & 131623.56 \\
1 / (x^1.01) & 1 / (x + 1000) & 127165.47 \\
1 / (x^1.01) & 1 / (x + 1) & 132268.30 \\
1 / (x^1.01) & 1 / 100 & 163117.40 \\
1 / (x^1.01) & 1 / 500 & 141385.79 \\
1 / (x^1.01) & 1 / 1000 & 135612.25 \\
1 / (x^1.01) & 1 / 5000 & 121905.50 \\
1 / (x^1.01) & 1 / 10000 & 119357.81 \\
1 / (x^1.01) & 1 / 50000 & 125141.06 \\
1 / (x^1.01) & 1 / (x + 1)^0.5 & 207099.32 \\
1 / (x^1.01) & 1 / (x + 1)^1.5 & 125699.71 \\
1 / (x^1.01) & 1 / (x + 1)^2 & 134929.54 \\
1 / (x^1.01) & 1 / ln(x + 1) & 418163.13 \\
1 / (x^1.01) & 1 / e^(x/3) & 135409.06 \\
1 / c & 1 / (x + 10) & 114051.47 \\
1 / c & 1 / (x + 100) & 114568.90 \\
1 / c & 1 / (x + 1000) & 118512.52 \\
1 / c & 1 / (x + 1) & 113998.26 \\
1 / c & 1 / 100 & 117521.60 \\
1 / c & 1 / 500 & 108969.41 \\
1 / c & 1 / 1000 & 111709.95 \\
1 / c & 1 / 5000 & 123741.66 \\
1 / c & 1 / 10000 & 127510.93 \\
1 / c & 1 / 50000 & 131542.49 \\
1 / c & 1 / (x + 1)^0.5 & 141554.07 \\
1 / c & 1 / (x + 1)^1.5 & 131329.66 \\
1 / c & 1 / (x + 1)^2 & 132709.43 \\
1 / c & 1 / ln(x + 1) & 309671.68 \\
1 / c & 1 / e^(x/3) & 132760.88 \\
1 / (x^0.5) & 1 / (x + 10) & 108638.55 \\
1 / (x^0.5) & 1 / (x + 100) & 108732.56 \\
1 / (x^0.5) & 1 / (x + 1000) & 110389.16 \\
1 / (x^0.5) & 1 / (x + 1) & 108630.68 \\
1 / (x^0.5) & 1 / 100 & 129035.87 \\
1 / (x^0.5) & 1 / 500 & 111706.58 \\
1 / (x^0.5) & 1 / 1000 & 109449.15 \\
1 / (x^0.5) & 1 / 5000 & 115147.43 \\
1 / (x^0.5) & 1 / 10000 & 120634.74 \\
1 / (x^0.5) & 1 / 50000 & 129963.25 \\
1 / (x^0.5) & 1 / (x + 1)^0.5 & 164079.31 \\
1 / (x^0.5) & 1 / (x + 1)^1.5 & 130185.66 \\
1 / (x^0.5) & 1 / (x + 1)^2 & 133876.06 \\
1 / (x^0.5) & 1 / ln(x + 1) & 340332.19 \\
1 / (x^0.5) & 1 / e^(x/3) & 134012.15 \\
\bottomrule
\end{tabular}