In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings

# warnings.filterwarnings('ignore')
plt.rcParams['figure.dpi'] = 80

import sys
sys.path.insert(0, '..')

import os
from pathlib import Path

from hypers import weight_hypers
from hypers import alpha_hypers 

from experiment import Params
from experiment import run_experiments
from experiment import load_experiments
from experiment import draw_logs
from experiment import experiments_to_df

from analysis import draw_several
from analysis import extract_needed

In [48]:
experiments_10, df_10 = load_experiments('../results/experim_10.json')
experiments_11, df_11 = load_experiments('../results/experim_11.json')
experiments_12, df_12 = load_experiments('../results/experim_12.json')
experiments_13, df_13 = load_experiments('../results/experim_13.json')
experiments_14, df_14 = load_experiments('../results/experim_14.json')
experiments_15, df_15 = load_experiments('../results/experim_15.json')
experiments_16, df_16 = load_experiments('../results/experim_16.json')
experiments_17, df_17 = load_experiments('../results/experim_17.json')
experiments_18, df_18 = load_experiments('../results/experim_18.json')
experiments_19, df_19 = load_experiments('../results/experim_19.json')
experiments_20, df_20 = load_experiments('../results/experim_20.json')
experiments_21, df_21 = load_experiments('../results/experim_21.json')
experiments_22, df_22 = load_experiments('../results/experim_22.json')
experiments_23, df_23 = load_experiments('../results/experim_23.json')
experiments_24, df_24 = load_experiments('../results/experim_24.json')
experiments_25, df_25 = load_experiments('../results/experim_25.json')
experiments_26, df_26 = load_experiments('../results/experim_26.json')
experiments_27, df_27 = load_experiments('../results/experim_27.json')
experiments_28, df_28 = load_experiments('../results/experim_28.json')
experiments_29, df_29 = load_experiments('../results/experim_29.json')
experiments_30, df_30 = load_experiments('../results/experim_30.json')
experiments_31, df_31 = load_experiments('../results/experim_31.json')
experiments_32, df_32 = load_experiments('../results/experim_32.json')
experiments_33, df_33 = load_experiments('../results/experim_33.json')
experiments_34, df_34 = load_experiments('../results/experim_34.json')
experiments_35, df_35 = load_experiments('../results/experim_35.json')
experiments_36, df_36 = load_experiments('../results/experim_36.json')
experiments_37, df_37 = load_experiments('../results/experim_37.json')
experiments_38, df_38 = load_experiments('../results/experim_38.json')
experiments_39, df_39 = load_experiments('../results/experim_39.json')
experiments_40, df_40 = load_experiments('../results/experim_40.json')
experiments_41, df_41 = load_experiments('../results/experim_41.json')
experiments_42, df_42 = load_experiments('../results/experim_42.json')
experiments_43, df_43 = load_experiments('../results/experim_43.json')
experiments_44, df_44 = load_experiments('../results/experim_44.json')
experiments_45, df_45 = load_experiments('../results/experim_45.json')
experiments_46, df_46 = load_experiments('../results/experim_46.json')
experiments_47, df_47 = load_experiments('../results/experim_47.json')
experiments_48, df_48 = load_experiments('../results/experim_48.json')
experiments_49, df_49 = load_experiments('../results/experim_49.json')
experiments_50, df_50 = load_experiments('../results/experim_50.json')
experiments_51, df_51 = load_experiments('../results/experim_51.json')
# experiments_52, df_52 = load_experiments('../results/experim_52.json')

In [61]:
experiments = experiments_17 + experiments_18 + experiments_19 + experiments_29 \
+ experiments_31 + experiments_33 + experiments_37 \
+ experiments_32 + experiments_49 + experiments_51 \
+ experiments_38 + experiments_48 + experiments_50

In [62]:
df = experiments_to_df(experiments)

In [69]:
pd.set_option('display.max_rows', None)
mt_mask = 1 #(df["mixing_type"] == "start") | (df["mixing_type"] == "uniform past")
table = df[(df["train_window"] == 10) & mt_mask]
# print(table[["weight_function", "mixing_type", "mean"]].to_latex(float_format="%.2f", index=False))
short = table[["alpha_function", "mixing_type", "weight_function", "mean"]]
# short
# print(short.to_latex(formatters= {"mean": lambda x: round(x / 10000, 2)}, index=False))
# print(short.to_latex(float_format="%.2f", index=False))
# short.shape

(168, 4)

In [11]:
df_29

,noise_var,train_window,weight_function,mixing_type,alpha_function,mean,random_0,random_1,random_2,random_3
1,1,10,1 / (x^1.01),start,1 / 10000,119357.81,104143.1,94267.86,145855.06,133165.22
4,1,10,1 / (x^1.01),start,1 / 50000,125141.06,111077.8,98557.9,153195.0,137733.52
3,1,10,1 / c,start,1 / 10000,127510.93,111944.6,100848.11,155241.4,142009.62
5,1,10,1 / c,start,1 / 50000,131542.49,115937.31,102532.38,160593.19,147107.09
2,1,10,1 / (x^0.5),start,1 / 10000,120634.74,106022.74,96704.84,148112.27,131699.12
0,1,10,1 / (x^0.5),start,1 / 50000,129963.25,114929.13,101955.53,159109.38,143858.96